language: cpp
sudo: required
dist: trusty
install:
  - sudo pip install conan
  - conan install --build=missing

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - ctest

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CC=gcc-6 CXX=g++-6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env: CC=clang-3.9 CXX=clang++-3.9
