os: linux
services:
  - docker
sudo: required
dist: trusty
language: cpp
install:
  - sudo pip install conan
  - conan install --build=missing

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - ctest

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
