build:
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan # It install conan too
  - conan install --build=missing

build_script:
  - mkdir build && cd build
  - cmake -G"Visual Studio 14 2015 Win64"
  - cmake --build . --config debug

test_script:
  - cmd: ctest -C debug -VV


